# Blog
title: Hannes Moser
email: box@hannes-moser.com
description: >
  I am a software developer with a slight faible for web platforms, services and API design. The last 15 years, I have worked on browser games, scalable websites, APIs and web applications.

baseurl: ""
url: "https://www.hannesmoser.at"
logo: /assets/images/author.jpg
cover: /assets/images/header.jpg

# Author
twitter_username: eliias
github_username:  eliias

author: Hannes Moser
author_image: /assets/images/author.jpg

# Settings
paginate: 5

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
